config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'live', to: 'stream#live'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController
  include ActionController::Live

  def live
    response.headers['Content-Type'] = 'text/event-stream'
    response.headers['Last-Modified'] = Time.now.httpdate

    sse = SSE.new(response.stream, retry: 300, event: 'Stream Started')

    sleep 1

    sse.write("The current time is #{Time.current}", event: 'Current time')

  rescue ActionController::Live::ClientDisconnected
    logger.info 'Client Disconnected'
    sse.close
    response.stream.close
  rescue IOError
    logger.info 'IOError'
    sse.close
    response.stream.close
  ensure
    sse.close
    response.stream.close
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">ActionController:Live Streaming</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= live_path %>">Stream</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionController Streaming</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5 pb-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div id="target"></div>

<script type="text/javascript">
  let source = new EventSource('/live');

  source.onopen = (event) => {
    console.log('The connection has been opened', event);
  }

  source.onmessage = (event) => {
    console.log('The message has been received', event);
    document.getElementById('target').innerHTML = event.data;
  }
</script>

app/views/stream/live.html.erb
<h1>Stream#live</h1>
<p>Find me in app/views/stream/live.html.erb</p>